# -*- coding: utf-8 -*-
"""
Report Agent 📄
===============
Specialist in synthesizing all agent results into a final pentest report.
Receives aggregated findings from all other agents.
"""
from __future__ import annotations
import json
import logging
from datetime import datetime

from backend.agent.agents.base_agent import BaseAgent

log = logging.getLogger("aavapt.agent.agents.report")


class ReportAgent(BaseAgent):
    NAME  = "report"
    ROLE  = "Pentest Report Specialist"
    EMOJI = "📄"
    TOOLS = [
        {
            "name": "generate_report",
            "description": "Generate final markdown pentest report from all findings",
            "parameters": {"format": "markdown or json"},
        },
        {
            "name": "finish",
            "description": "Done — deliver the final report",
            "parameters": {"answer": "complete pentest report"},
        },
    ]

    def __init__(self, aggregated_findings: list[dict] = None, agent_summaries: list[dict] = None):
        super().__init__()
        self._aggregated_findings = aggregated_findings or []
        self._agent_summaries = agent_summaries or []

    async def _execute(self, tool_name: str, args: dict, session_id: str, stream_cb) -> str:
        if tool_name == "generate_report":
            return await self._generate(args.get("format", "markdown"))
        return await super()._execute(tool_name, args, session_id, stream_cb)

    async def _generate(self, fmt: str) -> str:
        findings = self._aggregated_findings
        summaries = self._agent_summaries

        severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
        sorted_findings = sorted(findings, key=lambda f: severity_order.get(f.get("severity","info"), 4))

        counts = {}
        for f in findings:
            s = f.get("severity", "info")
            counts[s] = counts.get(s, 0) + 1

        if fmt == "json":
            return json.dumps({
                "generated_at": datetime.now().isoformat(),
                "finding_count": len(findings),
                "severity_counts": counts,
                "findings": sorted_findings,
                "agent_summaries": summaries,
            }, ensure_ascii=False, indent=2)

        # Markdown report
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        lines = [
            f"# Penetration Test Report",
            f"**Generated:** {now}  ",
            f"**Engine:** AA-VAPT Multi-Agent System  ",
            f"**Agents Used:** {', '.join(s.get('agent','?') for s in summaries)}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            f"Multi-agent pentest completed. **{len(findings)} findings** identified:",
            "",
        ]
        for sev in ["critical", "high", "medium", "low", "info"]:
            c = counts.get(sev, 0)
            if c:
                icons = {"critical":"🔴","high":"🟠","medium":"🟡","low":"🟢","info":"🔵"}
                lines.append(f"- {icons[sev]} **{sev.upper()}**: {c}")

        lines += ["", "---", "", "## Agent Summaries", ""]
        for s in summaries:
            lines.append(f"### {s.get('emoji','🤖')} {s.get('agent','?').title()} Agent")
            lines.append(f"- Steps: {s.get('steps', 0)}")
            lines.append(f"- Findings: {s.get('findings', 0)}")
            lines.append(f"- Status: {s.get('status','?')}")
            if s.get("answer"):
                lines.append(f"- Summary: {s['answer'][:300]}")
            lines.append("")

        lines += ["---", "", "## Findings Detail", ""]
        for i, f in enumerate(sorted_findings, 1):
            sev = f.get("severity", "info").upper()
            lines.append(f"### {i}. {f.get('name','?')} [{sev}]")
            if f.get("host"):
                lines.append(f"**Host:** `{f['host']}`{':'+str(f['port']) if f.get('port') else ''}")
            if f.get("source"):
                lines.append(f"**Source:** {f['source']}")
            if f.get("description"):
                lines.append(f"\n{f['description']}")
            lines.append("")

        lines += ["---", "", "## Recommendations", ""]
        if counts.get("critical", 0) or counts.get("high", 0):
            lines.append("⚠️ **Immediate action required** for Critical/High findings:")
            for f in sorted_findings:
                if f.get("severity") in ("critical","high"):
                    lines.append(f"- Remediate: {f.get('name','?')}")
        else:
            lines.append("No critical/high findings. Continue monitoring and patching medium/low items.")

        lines += ["", "---", "*Report generated by AA-VAPT Multi-Agent System*"]
        return "\n".join(lines)

    def _build_prompt(self, goal, target, last_obs, extra):
        summaries_str = json.dumps(self._agent_summaries, ensure_ascii=False, indent=2)[:2000]
        findings_str = json.dumps(self._aggregated_findings[:20], ensure_ascii=False)[:1500]
        return f"""You are 📄 report — Pentest Report Specialist.

GOAL: {goal}
AGENT SUMMARIES:
{summaries_str}

TOP FINDINGS ({len(self._aggregated_findings)} total):
{findings_str}

Generate the final report now. Use generate_report tool, then finish.

Respond ONLY with JSON:
{{"thought": "...", "action": "generate_report", "action_input": {{"format": "markdown"}}}}"""
