#!/bin/bash
# ══════════════════════════════════════════════════════════════
# AA-VAPT — Server Version Disclosure Verification Script
# Auto-generated from: Server-Q3.html
# Total targets: 119  (HTTPAPI: 111 | IIS/10: 7 | IIS/8.x: 1)
# Run from: Kali Linux with network access to target subnets
# Output: saved to ./aa-vapt-logs/server_version_results_<ts>.txt
# ══════════════════════════════════════════════════════════════

TIMEOUT=5
LOG_DIR="$(pwd)/aa-vapt-logs"; mkdir -p "$LOG_DIR"
OUT="${LOG_DIR}/server_version_results_$(date +%Y%m%d_%H%M%S).txt"
CONFIRMED=0; MISSING=0; TOTAL=0

# Check curl is available
if ! command -v curl &>/dev/null; then
  echo "[x] curl not found — install it: apt-get install curl"
  exit 1
fi

echo "════════════════════════════════════════════════════════" | tee "$OUT"
echo "  AA-VAPT — Server Version Disclosure Verification"      | tee -a "$OUT"
echo "  Total targets: 119"                                     | tee -a "$OUT"
echo "════════════════════════════════════════════════════════" | tee -a "$OUT"
echo "" | tee -a "$OUT"
echo "" | tee -a "$OUT"
echo "━━━ Microsoft-HTTPAPI/2.0  (111 targets) ━━━" | tee -a "$OUT"
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.100.102:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.100.102:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.100.102:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.100.102:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.100.90:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.100.90:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.100.90:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.100.90:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.101:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.101:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.101:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.101:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.101:8082 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.101:8082/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.101:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.101:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.106:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.106:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.106:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.106:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.132:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.132:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.150:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.150:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.164:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.164:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.164:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.164:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.19:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.19:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.196:443 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT https://172.16.101.196:443/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.196:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.196:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.196:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.196:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.197:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.197:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.198:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.198:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.198:8082 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.198:8082/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.198:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.198:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.206:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.206:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.21:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.21:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.21:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.21:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.211:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.211:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.211:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.211:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.22:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.22:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.230:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.230:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.230:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.230:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.230:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.230:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.32:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.32:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.32:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.32:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.7:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.7:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.88:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.88:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.88:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.88:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.94:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.94:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.106.11:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.106.11:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.106.11:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.106.11:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.106.12:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.106.12:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.106.12:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.106.12:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.5.141:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.5.141:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.5.141:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.5.141:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.124:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.124:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.23:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.23:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.23:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.23:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.24:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.24:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.24:8082 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.24:8082/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.24:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.24:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.31:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.31:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.31:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.31:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.35:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.35:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.51:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.51:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.52:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.52:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.6:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.6:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.6:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.6:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.150.10:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.150.10:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.150.10:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.150.10:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.99.19:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.99.19:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.99.22:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.99.22:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.101:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.101:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.101:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.101:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.101:8082 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.101:8082/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.101:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.101:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.104:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.104:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.104:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.104:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.2:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.2:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.3:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.3:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.3:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.3:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.3:8082 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.3:8082/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.3:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.3:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.45:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.45:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.45:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.45:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.61:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.61:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.62:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.62:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.62:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.62:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.65:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.65:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.71:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.71:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.72:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.72:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.72:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.72:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.81:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.81:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.81:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.81:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.82:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.82:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.82:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.82:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.82:8082 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.82:8082/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.82:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.82:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.86:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.86:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.86:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.86:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.87:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.87:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.87:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.87:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.91:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.91:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.100.92:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.100.92:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.21.101.10:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.21.101.10:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.21:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.21:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.21:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.21:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.24:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.24:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.24:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.24:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.28:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.28:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.28:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.28:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.4:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.4:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.4:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.4:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.44:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.44:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.44:17781 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.44:17781/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.44:17784 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.44:17784/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.44:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.44:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.45:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.45:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.55:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.55:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.70:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.70:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.70:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.70:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.88:5985 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.88:5985/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.22.100.88:47001 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.22.100.88:47001/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
echo "" | tee -a "$OUT"
echo "━━━ Microsoft-IIS/10.x  (7 targets) ━━━" | tee -a "$OUT"
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.132:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.132:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.196:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.196:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.198:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.198:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.24:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.24:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.31:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.31:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.31:8530 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.31:8530/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
TOTAL=$((TOTAL+1)); echo -n "[*] 172.17.100.52:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.17.100.52:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi
echo "" | tee -a "$OUT"
echo "━━━ Microsoft-IIS/8.x  (1 targets) ━━━" | tee -a "$OUT"
TOTAL=$((TOTAL+1)); echo -n "[*] 172.16.101.32:80 => " | tee -a "$OUT"; RESP=$(curl -sk -I --max-time $TIMEOUT http://172.16.101.32:80/ 2>/dev/null | grep -iE "^server:|^x-powered-by:|^x-aspnet"); if [ -n "$RESP" ]; then echo "$RESP" | tee -a "$OUT"; CONFIRMED=$((CONFIRMED+1)); else echo "No Server header / no response" | tee -a "$OUT"; MISSING=$((MISSING+1)); fi

echo "" | tee -a "$OUT"
echo "════════════════════════════════════════════════════════" | tee -a "$OUT"
echo "  SUMMARY" | tee -a "$OUT"
echo "  Total checked : $TOTAL" | tee -a "$OUT"
echo "  Confirmed leak: $CONFIRMED  (Server header visible)" | tee -a "$OUT"
echo "  No response   : $MISSING" | tee -a "$OUT"
echo "  Results saved : $OUT" | tee -a "$OUT"
echo "════════════════════════════════════════════════════════" | tee -a "$OUT"

# Show only confirmed version leaks
echo ""
echo "━━━ CONFIRMED VERSION LEAKS (filtered) ━━━"
grep -E "Microsoft|IIS|HTTPAPI|ASP" "$OUT" | grep -v "^━" | grep -v "^#"